### ISSUE TITLE
S905L3 U-Boot无法识别EMMC

### ISSUE THREAD

**Issue by a520ass** [ChalesYu/extdrv4openwrt#1]
大佬你好，有遇到过U-Boot下无法稳定识别emmc的问题吗，u-boot版本为2022.04 ，使用的p212_defconfig，修改了dts里面emmc的最大频率
https://github.com/ChalesYu/extdrv4openwrt/blob/64971b9bea73e8efc63c1eb8581703cb9c6addb7/aml-doc/S905X/guid.txt#L206

现象就是一会不能识别，一会能识别

![图片20220727151414](https://user-images.githubusercontent.com/8427401/181185154-8f777362-399a-41dc-badb-c8f0c255d0d7.png)

**Comment by nicktf-developer** [comment]
905L也存在同样的问题，我对照了905W dtb的emmc最大频率，和905x一样，无论改不改emmc节点最大频率，在armbian里无法识别出emmc

**Comment by a520ass** [comment]
> 905L也存在同样的问题，我对照了905W dtb的emmc最大频率，和905x一样，无论改不改emmc节点最大频率，在armbian里无法识别出emmc

改了dts，在armbian是能识别的，u-boot里面还是有问题

**Comment by ChalesYu** [comment]
#2  自行测试
